services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ssm-network
    ports:
      - "34115:34115"
      - "5173:5173"
    volumes:
      - .:/app
    tty: true

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ssm-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: admin
    ports:
      - 8081:80
    networks:
      - ssm-network

volumes:
  db_data:
    driver: local

networks:
  ssm-network:
    driver: bridge