// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateSQLFile(arg1:string):Promise<string>;

export function DeleteQuery(arg1:number):Promise<void>;

export function ExportDatabaseFile():Promise<void>;

export function GetQueriesList(arg1:boolean):Promise<Array<main.Query>>;

export function ImportDatabaseFile():Promise<void>;

export function InsertQueryInDatabase(arg1:main.Query):Promise<void>;

export function MakeBindedSQL(arg1:string,arg2:Array<{[key: string]: any}>,arg3:Array<main.Variable>):Promise<string>;

export function ReadXLSXFile():Promise<string>;

export function UpdateQuery(arg1:number,arg2:main.Query):Promise<void>;
