// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSQLFile(arg1) {
  return window['go']['main']['App']['CreateSQLFile'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadFile() {
  return window['go']['main']['App']['ReadFile']();
}
