// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckHasUpdate() {
  return window['go']['main']['App']['CheckHasUpdate']();
}

export function CreateOrUpdateDatabaseConnection(arg1) {
  return window['go']['main']['App']['CreateOrUpdateDatabaseConnection'](arg1);
}

export function CreateSQLFile(arg1) {
  return window['go']['main']['App']['CreateSQLFile'](arg1);
}

export function DeleteQuery(arg1) {
  return window['go']['main']['App']['DeleteQuery'](arg1);
}

export function ExportDatabaseFile() {
  return window['go']['main']['App']['ExportDatabaseFile']();
}

export function GetBuildParams() {
  return window['go']['main']['App']['GetBuildParams']();
}

export function GetDatabaseConnection() {
  return window['go']['main']['App']['GetDatabaseConnection']();
}

export function GetDatabaseStructure(arg1) {
  return window['go']['main']['App']['GetDatabaseStructure'](arg1);
}

export function GetLatestDatabaseStructure() {
  return window['go']['main']['App']['GetLatestDatabaseStructure']();
}

export function GetQueriesList(arg1) {
  return window['go']['main']['App']['GetQueriesList'](arg1);
}

export function ImportDatabaseFile() {
  return window['go']['main']['App']['ImportDatabaseFile']();
}

export function InsertQueryInDatabase(arg1) {
  return window['go']['main']['App']['InsertQueryInDatabase'](arg1);
}

export function MakeBindedSQL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeBindedSQL'](arg1, arg2, arg3, arg4);
}

export function ReadXLSXFile() {
  return window['go']['main']['App']['ReadXLSXFile']();
}

export function TestBatchQueryInDatabase(arg1, arg2) {
  return window['go']['main']['App']['TestBatchQueryInDatabase'](arg1, arg2);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['main']['App']['TestDatabaseConnection'](arg1);
}

export function TestQueryInDatabase(arg1, arg2) {
  return window['go']['main']['App']['TestQueryInDatabase'](arg1, arg2);
}

export function UpdateQuery(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuery'](arg1, arg2);
}
